create database chitu;
use chitu;
CREATE TABLE `regression_result` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `data_source_type` varchar(255) DEFAULT NULL COMMENT '数据源类型',
  `regression_type` varchar(255) DEFAULT NULL COMMENT '检测类型（数据一致性，是否丢失）',
  `job_type` varchar(255) DEFAULT NULL COMMENT '作业类型（普通kafka结构，cannal结构，表关联）',
  `table_name` varchar(255) DEFAULT NULL COMMENT '检测对应的表名称',
  `result` varchar(255) DEFAULT NULL COMMENT '检测的结果',
  `fail_detail` longtext COMMENT '错误明细内容',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `index_job_type` (`job_type`)
) ENGINE=InnoDB AUTO_INCREMENT=913 DEFAULT CHARSET=utf8mb4 COMMENT='connector数据集成测试结果';

CREATE TABLE `sdp_approve` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_name` varchar(255) DEFAULT NULL COMMENT '项目名称',
  `job_name` varchar(255) DEFAULT NULL COMMENT '作业名称',
  `approver` varchar(255) DEFAULT NULL,
  `approver2` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL COMMENT '审批状态',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
  `file_id` bigint(20) DEFAULT NULL,
  `remark` longtext,
  `description` longtext COMMENT '描述',
  `opinion` varchar(255) DEFAULT NULL,
  `opinion2` longtext,
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev',
  `created_by` varchar(128) DEFAULT NULL COMMENT '申请人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '申请时间',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '审批人',
  `updated_by2` varchar(255) DEFAULT NULL,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '审批时间',
  `updation_date2` timestamp NULL DEFAULT NULL,
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=573 DEFAULT CHARSET=utf8 COMMENT='申请审批表';

CREATE TABLE `sdp_data_source` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `data_source_name` varchar(255) DEFAULT NULL COMMENT '实例名称',
  `data_source_type` varchar(255) DEFAULT NULL COMMENT '数据源类型',
  `remark` text COMMENT '描述',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
  `owner` bigint(20) DEFAULT NULL COMMENT '责任人',
  `stream_load_url` text COMMENT 'stream load地址',
  `hbase_znode` varchar(255) DEFAULT NULL,
  `hadoop_conf_dir` varchar(255) DEFAULT NULL COMMENT 'hive hadoop配置目录',
  `hive_cluster` varchar(100) DEFAULT NULL COMMENT 'hive集群名称',
  `data_source_url` text COMMENT '数据源地址',
  `database_name` varchar(255) DEFAULT NULL COMMENT '数据库',
  `certify_type` varchar(255) DEFAULT 'default' COMMENT '认证方式',
  `user_name` varchar(255) DEFAULT NULL COMMENT '用户名',
  `password` varchar(255) DEFAULT NULL COMMENT '密码',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `hudi_catalog_path` varchar(255) DEFAULT NULL COMMENT 'hudi catalog 路径',
  PRIMARY KEY (`id`),
  KEY `index_project_id` (`project_id`)
) ENGINE=InnoDB AUTO_INCREMENT=357 DEFAULT CHARSET=utf8mb4 COMMENT='数据源管理表';

CREATE TABLE `sdp_data_source_mapping_rel` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uat_file_id` bigint(20) DEFAULT NULL COMMENT 'uat文件id',
  `prod_file_id` bigint(20) DEFAULT NULL COMMENT 'prod文件id',
  `uat_data_source_id` bigint(20) DEFAULT NULL COMMENT 'uat数据源id',
  `prod_data_source_id` bigint(20) DEFAULT NULL COMMENT '生产数据源id',
  `uat_data_source_name` varchar(255) DEFAULT NULL COMMENT 'uat 数据源名称',
  `uat_data_source_url` varchar(4000) DEFAULT NULL COMMENT 'uat数据源地址',
  `uat_data_source_type` varchar(255) DEFAULT NULL COMMENT 'uat数据源类型',
  `uat_meta_table_type` varchar(50) DEFAULT NULL COMMENT 'uat元表类型',
  `uat_meta_table_name` varchar(255) DEFAULT NULL COMMENT 'uat物理表名称',
  `prod_data_source_name` varchar(255) DEFAULT NULL COMMENT 'prod 数据源名称',
  `prod_data_source_url` varchar(4000) DEFAULT NULL COMMENT 'prod数据源地址',
  `prod_data_source_type` varchar(255) DEFAULT NULL COMMENT 'prod数据源类型',
  `prod_meta_table_type` varchar(50) DEFAULT NULL COMMENT 'prod元表类型',
  `prod_meta_table_name` varchar(255) DEFAULT NULL COMMENT 'prod物理表名称',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_uat` (`uat_file_id`,`uat_meta_table_name`) USING BTREE,
  KEY `idx_prod` (`prod_file_id`,`prod_meta_table_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=304 DEFAULT CHARSET=utf8mb4 COMMENT='转环境数据源映射关系表';

CREATE TABLE `sdp_dws_running_result` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `flink_job_id` varchar(100) NOT NULL COMMENT 'flink job id',
  `source_type` varchar(50) NOT NULL COMMENT '数据源类型',
  `database_table_name` varchar(400) NOT NULL COMMENT '数据库.表名。入库查询的时候需要拼接一下',
  `type` tinyint(4) NOT NULL COMMENT '0失败 1成功',
  `num` bigint(20) DEFAULT NULL COMMENT '成功数或者失败数',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev' COMMENT '环境',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uni_key` (`flink_job_id`,`source_type`,`database_table_name`,`type`)
) ENGINE=InnoDB AUTO_INCREMENT=514 DEFAULT CHARSET=utf8mb4 COMMENT='运行结果统计表';

CREATE TABLE `sdp_engine` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `engine_name` varchar(255) DEFAULT NULL COMMENT '引擎名称',
  `engine_version` varchar(255) DEFAULT NULL COMMENT '引擎版本',
  `engine_type` varchar(50) DEFAULT 'yarn' COMMENT '引擎类型：yarn、kubernetes',
  `uat_engine_queue` varchar(255) DEFAULT NULL COMMENT 'uat环境引擎队列',
  `uat_engine_cluster` varchar(255) DEFAULT NULL COMMENT 'uat环境引擎集群',
  `namespace` varchar(255) DEFAULT NULL COMMENT '生产k8s namespace',
  `uat_namespace` varchar(255) DEFAULT NULL COMMENT 'uat k8s namespace',
  `engine_queue` varchar(255) DEFAULT NULL COMMENT '引擎集群',
  `engine_cluster` varchar(255) DEFAULT NULL COMMENT '引擎集群',
  `engine_url` varchar(255) DEFAULT NULL COMMENT '引擎url',
  `business_flag` varchar(10) DEFAULT 'SDP',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=238 DEFAULT CHARSET=utf8mb4 COMMENT='引擎';


CREATE TABLE `sdp_engine_user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `engine_id` bigint(20) DEFAULT NULL COMMENT '引擎ID',
  `user_id` bigint(20) DEFAULT NULL COMMENT '用户ID',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=241 DEFAULT CHARSET=utf8mb4 COMMENT='引擎用户关系表';

CREATE TABLE `sdp_file` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `file_name` varchar(255) NOT NULL COMMENT '文件名称',
  `file_type` varchar(255) NOT NULL COMMENT '文件类型',
  `content` longtext,
  `etl_content` longtext CHARACTER SET utf8 COMMENT '转换语句sql',
  `meta_table_content` longtext CHARACTER SET utf8 COMMENT '元表sql',
  `config_content` longtext,
  `source_content` longtext,
  `data_stream_config` longtext CHARACTER SET utf8 COMMENT 'ds配置信息',
  `dag` longtext,
  `file_status` varchar(255) DEFAULT NULL COMMENT '文件状态',
  `business_flag` varchar(10) DEFAULT 'SDP',
  `locked_by` varchar(255) DEFAULT NULL COMMENT '锁定人',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
  `folder_id` bigint(20) DEFAULT NULL COMMENT '目录ID',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否可用',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志跟踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `need_approve` tinyint(4) DEFAULT '1' COMMENT '是否需要二级审批',
  `priority` tinyint(4) DEFAULT '2' COMMENT '作业优先级',
  `responsible` varchar(128) DEFAULT NULL COMMENT '负责人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2296 DEFAULT CHARSET=utf8mb4 COMMENT='文件';

CREATE TABLE `sdp_file_extra` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `business_value` longtext COMMENT '业务价值',
  `tech_specifications` longtext COMMENT '技术说明',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
  `file_id` bigint(20) DEFAULT NULL COMMENT '文件ID',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_index_file_id` (`file_id`)
) ENGINE=InnoDB AUTO_INCREMENT=643 DEFAULT CHARSET=utf8 COMMENT='任务价值';

CREATE TABLE `sdp_folder` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `folder_name` varchar(255) NOT NULL COMMENT '目录名称',
  `parent_id` bigint(20) DEFAULT NULL COMMENT '父目录ID',
  `project_id` bigint(20) NOT NULL COMMENT '项目ID',
  `business_flag` varchar(10) DEFAULT 'SDP',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否可用',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志跟踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=559 DEFAULT CHARSET=utf8mb4 COMMENT='目录';

CREATE TABLE `sdp_jar` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(255) DEFAULT NULL COMMENT 'jar名称',
  `version` varchar(255) DEFAULT NULL COMMENT 'jar版本',
  `flink_version1` varchar(20) DEFAULT NULL COMMENT 'flink版本',
  `flink_version` varchar(20) DEFAULT NULL COMMENT 'flink版本',
  `git` varchar(255) DEFAULT NULL COMMENT 'git地址',
  `url` varchar(255) DEFAULT NULL,
  `description` varchar(1500) DEFAULT NULL COMMENT 'jar描述',
  `project_id` bigint(20) DEFAULT NULL,
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=524 DEFAULT CHARSET=utf8 COMMENT='jar管理';

CREATE TABLE `sdp_job` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `job_name` varchar(255) NOT NULL COMMENT '作业名称',
  `job_content` longtext,
  `config_content` longtext,
  `source_content` longtext,
  `data_stream_config` longtext CHARACTER SET utf8 COMMENT 'ds配置信息',
  `running_version` varchar(255) DEFAULT NULL COMMENT '运行版本',
  `latest_version` varchar(255) DEFAULT NULL COMMENT '最新版本',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
  `file_id` bigint(20) DEFAULT NULL COMMENT '文件ID',
  `business_flag` varchar(10) DEFAULT 'SDP',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `priority` tinyint(4) DEFAULT '2' COMMENT '作业优先级',
  `responsible` varchar(128) DEFAULT NULL COMMENT '负责人',
  PRIMARY KEY (`id`),
  KEY `index_project_id` (`project_id`),
  KEY `index_file_id` (`file_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1820 DEFAULT CHARSET=utf8mb4 COMMENT='作业';

CREATE TABLE `sdp_job_alert_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `job_id` bigint(20) NOT NULL COMMENT '作业ID',
  `rule_id` bigint(20) NOT NULL COMMENT '规则ID',
  `alert_time` timestamp NOT NULL COMMENT '告警时间',
  `alert_content` varchar(1000) NOT NULL COMMENT '告警内容',
  `alert_num` int(4) DEFAULT NULL COMMENT '连续告警次数',
  `enabled_flag` tinyint(4) NOT NULL COMMENT '是否可用',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志跟踪ID',
  `created_by` varchar(128) NOT NULL COMMENT '创建人',
  `updated_by` varchar(128) NOT NULL COMMENT '更新人',
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_job_rule` (`job_id`,`rule_id`)
) ENGINE=InnoDB AUTO_INCREMENT=110704 DEFAULT CHARSET=utf8mb4 COMMENT='job告警记录';

CREATE TABLE `sdp_job_alert_rule` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `job_id` bigint(20) NOT NULL COMMENT '作业ID',
  `rule_generate_type` varchar(40) NOT NULL COMMENT '规则生成类型',
  `rule_name` varchar(128) NOT NULL COMMENT '规则名称',
  `rule_desc` varchar(255) NOT NULL COMMENT '规则描述',
  `index_name` varchar(128) DEFAULT NULL,
  `rule_content` varchar(255) NOT NULL COMMENT '规则内容',
  `effective_time` varchar(40) NOT NULL COMMENT '生效时间，例如00:00-10:00',
  `alert_rate` int(11) NOT NULL COMMENT '告警频率(分钟)',
  `notifi_type` varchar(255) DEFAULT NULL COMMENT '通知方式',
  `notify_users` varchar(800) NOT NULL COMMENT '通知用户',
  `effective_state` varchar(40) NOT NULL COMMENT '生效状态',
  `enabled_flag` tinyint(4) NOT NULL COMMENT '是否可用',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志跟踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `index_job_id` (`job_id`)
) ENGINE=InnoDB AUTO_INCREMENT=8004 DEFAULT CHARSET=utf8mb4 COMMENT='job告警规则';

CREATE TABLE `sdp_job_instance` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
  `job_id` bigint(20) DEFAULT NULL COMMENT '作业ID',
  `flink_job_id` varchar(255) DEFAULT NULL,
  `application_id` varchar(255) DEFAULT NULL,
  `jobmanager_address` varchar(200) DEFAULT NULL COMMENT 'k8s jobmanager地址',
  `configuration` longtext,
  `instance_info` longtext,
  `raw_status` varchar(255) DEFAULT NULL,
  `job_status` varchar(255) DEFAULT NULL COMMENT '作业状态',
  `expect_status` varchar(255) DEFAULT NULL,
  `job_version` varchar(255) DEFAULT NULL COMMENT '作业版本',
  `is_latest` tinyint(4) DEFAULT NULL,
  `flink_url` varchar(255) DEFAULT NULL,
  `version` bigint(20) DEFAULT '1',
  `job_content` longtext,
  `config_content` longtext,
  `source_content` longtext,
  `data_stream_config` longtext CHARACTER SET utf8 COMMENT 'ds配置信息',
  `execute_duration` bigint(20) DEFAULT NULL COMMENT '执行耗时',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `sign_status` varchar(255) DEFAULT NULL COMMENT '状态标识',
  PRIMARY KEY (`id`),
  KEY `index_job_id` (`job_id`)
) ENGINE=InnoDB AUTO_INCREMENT=58968 DEFAULT CHARSET=utf8mb4 COMMENT='作业实例';

CREATE TABLE `sdp_kafka_consumer_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `job_id` bigint(20) NOT NULL COMMENT 'sdp_job.id',
  `topic_name` varchar(255) NOT NULL COMMENT '主题名称',
  `ts` timestamp NULL DEFAULT NULL COMMENT '消费位置时间戳',
  `enabled_flag` tinyint(4) DEFAULT '1' COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev' COMMENT '环境',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uni_key` (`job_id`,`topic_name`,`enabled_flag`)
) ENGINE=InnoDB AUTO_INCREMENT=118716 DEFAULT CHARSET=utf8mb4 COMMENT='kafka 消费位置记录表';

CREATE TABLE `sdp_lineage_table_relation` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `file_id` bigint(20) NOT NULL COMMENT '文件ID',
  `job_id` bigint(20) NOT NULL COMMENT '作业ID',
  `job_name` varchar(255) NOT NULL COMMENT '作业名称',
  `source_data_source_type` varchar(40) NOT NULL COMMENT 'source数据源类型',
  `sink_data_source_type` varchar(40) NOT NULL COMMENT 'sink数据源类型',
  `source_data_source_url` varchar(1000) DEFAULT NULL COMMENT 'source数据源地址',
  `sink_data_source_url` varchar(1000) DEFAULT NULL COMMENT 'sink数据源地址',
  `source_database_name` varchar(255) DEFAULT NULL COMMENT 'source数据库',
  `sink_database_name` varchar(255) DEFAULT NULL COMMENT 'sink数据库',
  `source_table_name` varchar(255) NOT NULL COMMENT 'source表名',
  `sink_table_name` varchar(255) NOT NULL COMMENT 'sink表名',
  `env` varchar(10) DEFAULT 'dev',
  `enabled_flag` tinyint(4) NOT NULL COMMENT '是否可用',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志跟踪ID',
  `created_by` varchar(40) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(40) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_job_id` (`job_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1737 DEFAULT CHARSET=utf8mb4 COMMENT='表血缘关系';

CREATE TABLE `sdp_meta_table_config` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `file_id` bigint(20) NOT NULL COMMENT '文件id',
  `flink_table_name` varchar(255) DEFAULT NULL COMMENT '元表名称|元表引用名称',
  `data_source_id` bigint(20) NOT NULL COMMENT '数据源id',
  `meta_table_name` varchar(255) DEFAULT NULL COMMENT '物理表名',
  `meta_table_type` varchar(50) DEFAULT NULL COMMENT '元表类型',
  `flink_ddl` text NOT NULL COMMENT 'flink_ddl',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否可用',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志跟踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `index_datasource_id` (`data_source_id`),
  KEY `index_file_id` (`file_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10456 DEFAULT CHARSET=utf8mb4 COMMENT='元表配置';

CREATE TABLE `sdp_meta_table_relation` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `file_id` bigint(20) NOT NULL COMMENT '文件ID',
  `database_name` varchar(255) DEFAULT NULL COMMENT '数据库名',
  `meta_table_name` varchar(255) DEFAULT NULL COMMENT '物理表名',
  `meta_table_type` varchar(50) DEFAULT NULL COMMENT '元表类型',
  `data_source_id` bigint(20) DEFAULT NULL COMMENT '数据源ID',
  `meta_table_id` bigint(20) DEFAULT NULL COMMENT '元表ID',
  `flink_table_name` varchar(255) DEFAULT NULL COMMENT '元表名称|元表引用名称',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否可用',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志跟踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `index_datasource_id` (`data_source_id`),
  KEY `index_file_id` (`file_id`)
) ENGINE=InnoDB AUTO_INCREMENT=48142 DEFAULT CHARSET=utf8mb4 COMMENT='元表关系';

CREATE TABLE `sdp_operation_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `action` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `from_expect_status` varchar(255) DEFAULT NULL,
  `to_expect_status` varchar(255) DEFAULT NULL,
  `message` longtext,
  `instance_id` bigint(20) DEFAULT NULL COMMENT '实例ID',
  `flink_log` longtext,
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_instance_id` (`instance_id`)
) ENGINE=InnoDB AUTO_INCREMENT=53404 DEFAULT CHARSET=utf8 COMMENT='操作日志';

CREATE TABLE `sdp_pro_job_table_detail` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` bigint(20) NOT NULL COMMENT '项目ID',
  `project_name` varchar(255) NOT NULL COMMENT '项目名称',
  `project_level` varchar(20) NOT NULL COMMENT '项目等级',
  `product_line_code` varchar(128) DEFAULT NULL COMMENT '业务线code',
  `product_line_name` varchar(128) DEFAULT NULL COMMENT '业务线名称',
  `file_id` bigint(20) NOT NULL COMMENT '文件ID',
  `file_name` varchar(255) NOT NULL COMMENT '文件名称',
  `job_id` bigint(20) NOT NULL COMMENT '作业ID',
  `job_type` varchar(40) NOT NULL COMMENT '作业类型',
  `job_name` varchar(255) NOT NULL COMMENT '作业名称',
  `job_owner_number` varchar(50) DEFAULT NULL COMMENT '作业负责人工号',
  `job_owner` varchar(128) DEFAULT NULL COMMENT '作业负责人',
  `job_jm_memory` varchar(20) NOT NULL COMMENT '作业job manager内存',
  `job_tm_memory` varchar(20) NOT NULL COMMENT '作业task manager内存',
  `job_parallelism` int(11) NOT NULL COMMENT '作业并行度',
  `job_engine_name` varchar(128) NOT NULL COMMENT '作业计算引擎',
  `job_engine_version` varchar(80) DEFAULT NULL COMMENT '作业引擎版本',
  `job_jar_name` varchar(128) DEFAULT NULL COMMENT '作业udx资源文件名',
  `job_jar_version` varchar(80) DEFAULT NULL COMMENT '作业udx资源文件版本',
  `job_created_by` varchar(40) DEFAULT NULL COMMENT '作业创建人',
  `job_updated_by` varchar(40) DEFAULT NULL COMMENT '作业更新人',
  `job_creation_date` timestamp NULL DEFAULT NULL COMMENT '作业创建时间',
  `job_updation_date` timestamp NULL DEFAULT NULL COMMENT '作业修改时间',
  `data_source_type` varchar(40) NOT NULL COMMENT '数据源类型',
  `data_source_url` varchar(1000) DEFAULT NULL COMMENT '数据源地址',
  `database_name` varchar(255) DEFAULT NULL COMMENT '数据库',
  `flink_table_name` varchar(255) DEFAULT NULL COMMENT 'flink元表引用名称',
  `meta_table_name` varchar(255) NOT NULL COMMENT '物理表名',
  `meta_table_type` varchar(20) NOT NULL COMMENT '元表类型(source/sink)',
  `env` varchar(10) DEFAULT 'dev',
  `enabled_flag` tinyint(4) NOT NULL COMMENT '是否可用',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志跟踪ID',
  `created_by` varchar(40) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(40) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_job_id` (`job_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2673 DEFAULT CHARSET=utf8mb4 COMMENT='项目作业表明细';

CREATE TABLE `sdp_project` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_name` varchar(255) DEFAULT NULL COMMENT '项目名称',
  `project_code` varchar(255) DEFAULT NULL,
  `business_flag` varchar(10) DEFAULT 'SDP',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `product_line_name` varchar(128) DEFAULT NULL,
  `product_line_code` varchar(128) DEFAULT NULL,
  `priority` tinyint(4) DEFAULT '2' COMMENT '项目优先级',
  `app_key` varchar(500) DEFAULT NULL COMMENT '应用中心的appKey，datahub认证使用到',
  `app_secret` varchar(500) DEFAULT NULL COMMENT '应用中心的appSecret，datahub认证需要用到',
  `forbid_udx_updation` int(11) DEFAULT '1' COMMENT '禁止UDX资源同一版本内更新 1禁止，0不禁止',
  `allow_job_add_edit` int(11) DEFAULT '0' COMMENT '允许生产环境新增作业与编辑作业代码 1:允许，0不允许',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=345 DEFAULT CHARSET=utf8mb4 COMMENT='项目';

CREATE TABLE `sdp_project_engine` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
  `engine_id` bigint(20) DEFAULT NULL COMMENT '引擎ID',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=555 DEFAULT CHARSET=utf8mb4 COMMENT='项目引擎关系表';

CREATE TABLE `sdp_project_user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
  `user_id` bigint(20) DEFAULT NULL COMMENT '用户ID',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `is_leader` tinyint(4) DEFAULT NULL COMMENT '是否负责人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3746 DEFAULT CHARSET=utf8mb4 COMMENT='项目用户关系表';

CREATE TABLE `sdp_raw_status_history` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `job_id` bigint(20) DEFAULT NULL COMMENT '作业ID',
  `instance_id` bigint(20) DEFAULT NULL COMMENT '实例ID',
  `from_status` varchar(255) DEFAULT NULL,
  `to_status` varchar(255) DEFAULT NULL,
  `trigger` varchar(255) DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=113486 DEFAULT CHARSET=utf8mb4 COMMENT='作业状态历史';

CREATE TABLE `sdp_runtime_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `job_id` bigint(20) NOT NULL COMMENT '作业id',
  `job_instance_id` bigint(20) DEFAULT NULL COMMENT '作业实例id',
  `operation` varchar(255) DEFAULT NULL COMMENT '运行操作',
  `operation_stage` varchar(255) DEFAULT NULL COMMENT '运行状态',
  `yarn_log_url` varchar(255) DEFAULT NULL COMMENT 'yarn日志链接',
  `k8s_log_url` varchar(1024) DEFAULT NULL,
  `flink_log_url` varchar(255) DEFAULT NULL COMMENT 'flink日志链接',
  `stack_trace` longtext,
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `step_action` varchar(255) DEFAULT NULL COMMENT '运行步骤',
  `operation_time` timestamp(3) NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '操作时间格式为yyyy-MM-dd HH:mm:ss.SSS',
  PRIMARY KEY (`id`),
  KEY `index_job_id` (`job_id`),
  KEY `index_operation_time` (`operation_time`)
) ENGINE=InnoDB AUTO_INCREMENT=76045 DEFAULT CHARSET=utf8 COMMENT='运行日志';

CREATE TABLE `sdp_savepoint` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `job_id` bigint(20) NOT NULL COMMENT 'sdp_job.id',
  `savepoint_name` varchar(255) DEFAULT NULL COMMENT '保存点名称',
  `trigger_time` datetime NOT NULL COMMENT '触发时间',
  `file_path` varchar(1000) DEFAULT NULL COMMENT '保存点路径',
  `operate_status` varchar(255) DEFAULT NULL COMMENT '操作状态',
  `operate_err_msg` text COMMENT '操作异常信息',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev' COMMENT '环境',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=240 DEFAULT CHARSET=utf8mb4 COMMENT='保存点记录信息';

CREATE TABLE `sdp_sys_config` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `config_key` varchar(255) DEFAULT NULL COMMENT '配置类型key',
  `config_value` text COMMENT '配置value',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否可用',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=utf8mb4 COMMENT='系统配置表';

CREATE TABLE `sdp_token` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL,
  `token` varchar(100) NOT NULL COMMENT 'token',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `trace_id` varchar(32) DEFAULT NULL,
  `enabled_flag` int(1) DEFAULT '1' COMMENT '是否有效',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(64) DEFAULT NULL COMMENT '最后更新人',
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token` (`token`)
) ENGINE=InnoDB AUTO_INCREMENT=154 DEFAULT CHARSET=utf8mb4 COMMENT='用户Token';

CREATE TABLE `sdp_uat_job_running_config` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `job_id` bigint(20) NOT NULL COMMENT 'sdp_job.id',
  `days` int(11) DEFAULT '3' COMMENT '运行时长,单位：天,值是-1代表永久有效',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `env` varchar(10) DEFAULT 'dev' COMMENT '环境',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=425 DEFAULT CHARSET=utf8mb4 COMMENT='UAT环境作业运行配置';

CREATE TABLE `sdp_user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_name` varchar(255) NOT NULL COMMENT '用户姓名',
  `employee_number` varchar(255) DEFAULT NULL COMMENT '员工工号',
  `private_mobile` varchar(255) DEFAULT NULL,
  `employee_id` varchar(255) DEFAULT NULL,
  `is_admin` tinyint(4) DEFAULT NULL COMMENT '是否管理员',
  `project_id` bigint(20) DEFAULT NULL,
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否有效',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `last_login` timestamp NULL DEFAULT NULL,
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `role_id` bigint(20) DEFAULT '1' COMMENT 'datahub角色id，默认是1普通用户，对应datahub_role的记录',
  `department` varchar(255) DEFAULT NULL COMMENT '部门',
  `duty` varchar(255) DEFAULT NULL COMMENT '岗位',
  `password` varchar(255) DEFAULT NULL,
  `email` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `employee_index` (`employee_number`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1944 DEFAULT CHARSET=utf8mb4 COMMENT='用户';

CREATE TABLE `sdp_version` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `file_name` varchar(255) DEFAULT NULL,
  `file_version` varchar(255) DEFAULT NULL COMMENT '版本号',
  `file_content` longtext,
  `meta_table_json` longtext CHARACTER SET utf8 COMMENT '元表json',
  `etl_content` longtext CHARACTER SET utf8 COMMENT '转换语句sql',
  `meta_table_content` longtext CHARACTER SET utf8 COMMENT '元表sql',
  `config_content` longtext,
  `source_content` longtext,
  `data_stream_config` longtext CHARACTER SET utf8 COMMENT 'ds配置信息',
  `remark` varchar(1500) DEFAULT NULL COMMENT '备注',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
  `file_id` bigint(20) DEFAULT NULL COMMENT '文件ID',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否可用',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志追踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `responsible` varchar(128) DEFAULT NULL COMMENT '负责人',
  PRIMARY KEY (`id`),
  KEY `idx_file_id` (`file_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4999 DEFAULT CHARSET=utf8mb4 COMMENT='版本';

CREATE TABLE `test_db` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `file_id` bigint(20) NOT NULL COMMENT '文件id',
  `flink_table_name` varchar(255) DEFAULT NULL COMMENT '元表名称|元表引用名称',
  `data_source_id` bigint(20) NOT NULL COMMENT '数据源id',
  `meta_table_name` varchar(255) DEFAULT NULL COMMENT '物理表名',
  `meta_table_type` varchar(50) DEFAULT NULL COMMENT '元表类型',
  `flink_ddl` text NOT NULL COMMENT 'flink_ddl',
  `enabled_flag` tinyint(4) DEFAULT NULL COMMENT '是否可用',
  `env` varchar(10) DEFAULT 'dev',
  `trace_id` varchar(128) DEFAULT NULL COMMENT '日志跟踪ID',
  `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(128) DEFAULT NULL COMMENT '更新人',
  `creation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `index_datasource_id` (`data_source_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5097 DEFAULT CHARSET=utf8mb4 COMMENT='元表配置';

-- 初始化数据
INSERT INTO sdp_user (user_name, employee_number, private_mobile, is_admin, enabled_flag, password, email)
VALUES ('admin', 'admin', '18825195488', 1, 1,  '123456', '745596015@qq.com');
